[input]
html_selector = "article"
base_directory = "output"

[[input.files]]
path = "pages/chyba.html"
url = "/pages/chyba.html"
title = "ChybaÂ ğŸ›"

[[input.files]]
path = "pages/o-mne.html"
url = "/pages/o-mne.html"
title = "OÂ mnÄ›"

[[input.files]]
path = "site.html"
url = "/site.html"
title = "SÃ­tÄ›"

[[input.files]]
path = "git.html"
url = "/git.html"
title = "Git"

[[input.files]]
path = "mit.html"
url = "/mit.html"
title = "MIT"

[[input.files]]
path = "deleni-v-pevne-radove-carce.html"
url = "/deleni-v-pevne-radove-carce.html"
title = "DÄ›lenÃ­ v pevnÃ© Å™adovÃ©Â ÄÃ¡rce"

[[input.files]]
path = "dbi.html"
url = "/dbi.html"
title = "DBI"

[[input.files]]
path = "prg.html"
url = "/prg.html"
title = "PRG"

[[input.files]]
path = "psk.html"
url = "/psk.html"
title = "PSK"

[[input.files]]
path = "stm8oss.html"
url = "/stm8oss.html"
title = "VÃ½voj STM8 s OpenSourceÂ nÃ¡stroji"

[[input.files]]
path = "vscodecodium.html"
url = "/vscodecodium.html"
title = "VSCode/Codium"

[[input.files]]
path = "chocolatey.html"
url = "/chocolatey.html"
title = "Chocolatey"

[[input.files]]
path = "pip-a-venv.html"
url = "/pip-a-venv.html"
title = "pip aÂ venv"

[[input.files]]
path = "ultrazvukovy-meric-vzdalenosti-pomoci-timeru-tim2.html"
url = "/ultrazvukovy-meric-vzdalenosti-pomoci-timeru-tim2.html"
title = "UltrazvukovÃ½ mÄ›Å™iÄ vzdÃ¡lenosti pomocÃ­ timeru TIM2"

[[input.files]]
path = "pouziti-casovace-jako-generatoru-pwm.html"
url = "/pouziti-casovace-jako-generatoru-pwm.html"
title = "PouÅ¾itÃ­ ÄasovaÄe jako generÃ¡toru PWM"

[[input.files]]
path = "generovani-zvuku-zaklady.html"
url = "/generovani-zvuku-zaklady.html"
title = "GenerovÃ¡nÃ­ zvuku â€”Â zÃ¡klady"

[[input.files]]
path = "zakladni-pouziti-casovace.html"
url = "/zakladni-pouziti-casovace.html"
title = "ZÃ¡kladnÃ­ pouÅ¾itÃ­Â ÄasovaÄe"

[[input.files]]
path = "cecko-pac-veci-kterych-byste-si-fakt-meli-vsimnout.html"
url = "/cecko-pac-veci-kterych-byste-si-fakt-meli-vsimnout.html"
title = "CÃ©Äko â€” pÃ¡c vÄ›cÃ­, kterÃ½ch byste si fakt mÄ›liÂ vÅ¡imnout"

[[input.files]]
path = "oddelena-kompilace-a-vlastni-knihovny.html"
url = "/oddelena-kompilace-a-vlastni-knihovny.html"
title = "OddÄ›lenÃ¡ kompilace a vlastnÃ­Â knihovny"
